import Head from 'next/head'
import Link from 'next/link'

import styles from '../../styles/Home.module.css'

export async function getServerSideProps(context) {

    const response = await fetch(`http://localhost:3000/api/movie/${context.params.id}`)
    const json = await response.json()

    return {
        props: {
            info: json.info
        }
    }
}

export default function MovieItem({ info }) {
  
  const data = info.release_date = new Date()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/">
           Buscar
      </Link>
      <main className={styles.main}>
        <h1 className={styles.title}>
          {info.title} {data.getFullYear()}
        </h1>
        <p>Nota: {info.vote_average}</p>
        <p>{info.overview}</p>
        <img src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} width="400"/>
      </main>
    </div>
  )
}