import Head from 'next/head'

import styles from '../styles/Home.module.css'

export async function getStaticProps() {

  return {
    props: {
      author: 'Bruno'
    }
  }
}

export default function Home({author}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sobre o sistema
        </h1>

        autor: {author}

      </main>
    </div>
  )
}